apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
          env:
            - name: JWT_SECRET
              value: "{{ .Values.env.JWT_SECRET }}"
            - name: REDIS_ADDR
              value: "{{ .Values.env.REDIS_ADDR }}"
          resources: {{- toYaml .Values.resources | nindent 10 }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path }}
              port: 8080
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.path }}
              port: 8080
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
          startupProbe:
            httpGet:
              path: {{ .Values.probes.startup.path }}
              port: 8080
            initialDelaySeconds: {{ .Values.probes.startup.initialDelaySeconds }}
          terminationMessagePolicy: File
          terminationMessagePath: /dev/termination-log
      restartPolicy: Always