apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  selector:
    app: auth-service
  type: ClusterIP
  ports:
    - name: main
      protocol: TCP
      port: {{ .Values.service.main.port }}
      targetPort: {{ .Values.service.main.targetPort }}
