replicaCount: 2

image:
  repository: kostuwan/auth-service
  tag: latest

service:
  port: 8080

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "200m"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60

env:
  JWT_SECRET: "anime-platform-dev-secret-12345"
  REDIS_ADDR: "redis-master:6379"
  GRAYLOG_ENDPOINT: "graylog:12201"
  

probes:
  liveness:
    path: /healthz
    initialDelaySeconds: 5
  readiness:
    path: /ready
    initialDelaySeconds: 3
  startup:
    path: /startup
    initialDelaySeconds: 10
