apiVersion: v1
kind: ConfigMap
metadata:
  name: krakend-config
  labels:
    app.kubernetes.io/name: krakend
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name | quote }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace | quote }}
data:
  krakend.json: |
    {
      "version": 3,
      "name": "Anime Gateway",
      "port": 8080,
      "extra_config": {
        "github_com/devopsfaith/krakend-jose": {
          "alg": "HS256",
          "secret": "anime-platform-dev-secret-12345"
        }
      },
      "endpoints": [
        {
          "endpoint": "/auth/login",
          "method": "POST",
          "backend": [{"url_pattern": "/login", "host": ["http://auth-service:8080"]}]
        },
        {
          "endpoint": "/catalog",
          "method": "GET",
          "extra_config": {
            "github_com/devopsfaith/krakend-jose/validator": {
              "alg": "HS256",
              "audience": ["anime-platform"]
            }
          },
          "backend": [{"url_pattern": "/anime", "host": ["http://catalog-service:8080"]}]
        }
      ]
    }