apiVersion: apps/v1
kind: Deployment
metadata:
  name: krakend
  labels:
    app: krakend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: krakend
  template:
    metadata:
      labels:
        app: krakend
    spec:
      containers:
        - name: krakend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config
              mountPath: /etc/krakend
          resources: {{- toYaml .Values.resources | nindent 10 }}
          livenessProbe:
            httpGet:
              path: /__health
              port: 8080
            initialDelaySeconds: 5
          readinessProbe:
            httpGet:
              path: /__stats
              port: 8080
            initialDelaySeconds: 3
      volumes:
        - name: config
          configMap:
            name: krakend-config