apiVersion: v1
kind: Service
metadata:
  name: krakend
  labels:
    app: krakend
spec:
  selector:
    app: krakend
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8080