apiVersion: v1
kind: Service
metadata:
  name: watch-service
  labels:
    app: watch-service
spec:
  selector:
    app: watch-service
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8080