apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensearch
  labels:
    app: opensearch
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: opensearch
  template:
    metadata:
      labels:
        app: opensearch
    spec:
      restartPolicy: Always
      containers:
        - name: opensearch
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 9200
          env:
            - name: discovery.type
              value: {{ index .Values.env "discovery.type" | quote }}
            - name: DISABLE_SECURITY_PLUGIN
              value: {{ .Values.env.DISABLE_SECURITY_PLUGIN | quote }}
            - name: bootstrap.memory_lock
              value: {{ index .Values.env "bootstrap.memory_lock" | quote }}
            - name: OPENSEARCH_JAVA_OPTS
              value: {{ .Values.env.OPENSEARCH_JAVA_OPTS | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /
              port: 9200
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.readiness.failureThreshold }}
          livenessProbe:
            httpGet:
              path: /
              port: 9200
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold }}
          startupProbe:
            httpGet:
              path: /
              port: 9200
            initialDelaySeconds: {{ .Values.probes.startup.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.startup.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.startup.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.startup.failureThreshold }}
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
  labels:
    app: opensearch
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9200
  selector:
    app: opensearch
---
{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: opensearch-hpa
  labels:
    app: opensearch
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: opensearch
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetMemoryUtilizationPercentage }}
{{- end }}
